typedef struct _DEVICE_EXTENSION
{
	USHORT			fecha;
	WDFDEVICE		ControlDevice;
	WDFUSBDEVICE    UsbDevice;
} DEVICE_EXTENSION, * PDEVICE_EXTENSION;
WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(DEVICE_EXTENSION, GetDeviceExtension);

typedef struct _CONTROL_EXTENSION
{
	PDEVICE_EXTENSION devExt;
} CONTROL_EXTENSION, *PCONTROL_EXTENSION;
WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(CONTROL_EXTENSION, GetControlExtension);

#ifdef _HIDFILTER_

DRIVER_INITIALIZE DriverEntry;

EVT_WDF_DRIVER_DEVICE_ADD HF_AddDevice;

NTSTATUS IniciarInterfazControl(IN WDFDRIVER Driver, IN PDEVICE_EXTENSION devExt);

EVT_WDF_DEVICE_PREPARE_HARDWARE  EvtDevicePrepareHardware;

EVT_WDF_OBJECT_CONTEXT_CLEANUP EvtCleanupCallback;

#endif