#ifdef _PUBLIC_
NTSTATUS IniciarIoCtlAplicacion(_In_ WDFDEVICE device);
VOID CerrarIoCtlAplicacion(_In_ WDFDEVICE device);
#endif // _PUBLIC_

#ifdef _PRIVATE_
#define IOCTL_X52			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0800, METHOD_BUFFERED, FILE_WRITE_ACCESS)
#define IOCTL_TEXTO			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0801, METHOD_BUFFERED, FILE_WRITE_ACCESS)


typedef struct _CONTROL_CONTEXT
{
	WDFQUEUE Cola;
	WDFDEVICE Padre;
} CONTROL_CONTEXT, *PCONTROL_CONTEXT;
WDF_DECLARE_CONTEXT_TYPE_WITH_NAME(CONTROL_CONTEXT, GetControlContext);

EVT_WDF_IO_QUEUE_IO_DEVICE_CONTROL EvtIOCtlAplicacion;
#endif


